image: docker.io/qazando/appium-maven

stages:
  - test

Ja√ßa-job:
  stage: test
  script:
    # primeiro comando abaixo instala o maestro
    - curl -Ls "https://get.maestro.mobile.dev" | bash
    # e para configurar a variavel de ambiente do maestro
    - export PATH="$PATH":"$HOME/.maestro/bin"
    # comando e apikey tem que ser a sua
    - maestro cloud --apiKey rb_K3wochNOVbEIa9YhKr9gEu3u6x8nxHy5btuqYdgSv5MeZ01mXqK1hypM97xbGf5yiKqf8H3nx9cp56JC97nOWmjcnjv8IoEDEn7 qazandoqafood.apk .maestro/
    # este e nossa pipeline para rodar no gitlab
