name: Build and run Maestro tests (Native Android)

on:
  push:
    branches: 
      - master
  

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: docker.io/cypress/browsers
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
       
        name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 14
      
      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
        with:
          api-key: rb_E8v2oOlcjbOA7IKLyZS5jKGacLWg7iy3iN4SgvfSPjHjBbjsMzUm2M1GxTOCrif1Y4aY1cYRoTzJgzPQ86C6x6GJmxuWQXxgKWh
          app-file: qazandoqafood.apk
          